[versions]
androidGradlePlugin = "8.2.0-beta06"
kotlinAndroidPlugin = "1.9.20-Beta2"

kotlinVersion = "1.9.0"
androidXCoreVersion = "1.12.0"
appCompatVersion = "1.6.1"
coroutinesVersion = "1.7.1"
coordinatorLayoutVersion = "1.2.0"
constraintLayoutVersion = "2.1.4"
recyclerViewVersion = "1.3.2"
zxcvbnVersion = "1.3.1"
timberVersion = "4.7.1"
leakCanaryVersion = "2.7"
lifecycleKtxVersion = "2.6.2"
kotpassVersion = "0.6.1"
okioVersion = "3.2.0"
coilVersion = "2.4.0"

########################################################
# Not upgrate until found a way to use BiometricConsants
biometricsVersion = "1.0.1"
########################################################

documentfileVersion = "1.0.1"

junitVersion = "4.13.1"
espressoVersion = "3.4.0"
androidTestVersion = "1.1.0"
kaspressoVersion = "1.4.3"

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinAndroidPlugin" }

[libraries]
kotlinStdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlinVersion" }
androidXCore = { module = "androidx.core:core", version.ref = "androidXCoreVersion" }
appCompat = { module = "androidx.appcompat:appcompat", version.ref = "appCompatVersion" }
coroutinesCore = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutinesVersion" }
coroutinesAndroid = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutinesVersion" }
coordinatorLayout = { module = "androidx.coordinatorlayout:coordinatorlayout", version.ref = "coordinatorLayoutVersion" }
constraintLayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintLayoutVersion" }
recyclerView = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerViewVersion" }
zxcvbn = { module = "com.nulab-inc:zxcvbn", version.ref = "zxcvbnVersion" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timberVersion" }
leakCanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakCanaryVersion" }
lifecycleKtx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleKtxVersion" }
kotpass = { module = "com.github.keemobile:kotpass", version.ref = "kotpassVersion" }
okio = { module = "com.squareup.okio:okio", version.ref = "okioVersion" }
coil = { module = "io.coil-kt:coil", version.ref = "coilVersion" }
biometrics = { module = "androidx.biometric:biometric", version.ref = "biometricsVersion" }
documentfile = { module = "androidx.documentfile:documentfile", version.ref = "documentfileVersion" }

test-junit = { module = "junit:junit", version.ref = "junitVersion" }
test-coroutinesTest = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutinesVersion" }
test-kaspresso = { module = "com.kaspersky.android-components:kaspresso", version.ref = "kaspressoVersion" }
test-espressoIntents = { module = "androidx.test.espresso:espresso-intents", version.ref = "espressoVersion" }
test-androidTestRunner = { module = "androidx.test:runner", version.ref = "androidTestVersion" }
test-androidTestRules = { module = "androidx.test:rules", version.ref = "androidTestVersion" }
test-androidTestExt = { module = "androidx.test.ext:junit-ktx", version.ref = "androidTestVersion" }
test-androidTestCoreKtx = { module = "androidx.test:core-ktx", version.ref = "androidTestVersion" }
